[mypy]
python_version = 3.13
files = src
check_untyped_defs = True
warn_return_any = False
warn_unused_ignores = True
no_implicit_optional = True
ignore_missing_imports = True
explicit_package_bases = True
mypy_path = src

[mypy-requests.*]
ignore_missing_imports = True
