from __future__ import annotations

from core.command_context import CommandContext
import random

MEOWS = [
    "meow",
    "miaow",
    "mew",
    "miau",
    "miaou",
    "miao",
    "miyav",
    "mjau",
    "mjouw",
    "mjauu",
    "nya",
    "nyan",
    "nyaa",
    "nyā",
    "nyau",
    "nyaw",
    "nyow",
    "ngeo",
    "ngiau",
    "ngiyaw",
    "yaong",
    "yaung",
    "yaoong",
    "ngeong",
    "neko-nya",
    "nya-nya",
    "nyan-nyan",
    "mya",
    "myaa",
    "myau",
    "mraow",
    "mrrow",
    "mrow",
    "mrrp",
    "mrrrow",
    "prrrow",
    "purr-meow",
    "mewmew",
    "mew-mew",
    "meow-meow",
    "maow",
    "meeow",
    "mee-ow",
    "miav",
    "miow",
    "mioo",
    "miu",
    "miyau",
    "miyow",
    "miyawu",
    "mjav",
    "mjov",
    "mjao",
    "mjaou",
    "mjau-mjau",
    "miau-miau",
    "miaou-miaou",
    "miao-miao",
    "meo-meo",
    "nyao",
    "nyao-nyao",
    "nyawa",
    "nyawa-nya",
    "nyaaaan",
    "nyoro",
    "nrrya",
    "nyrr",
    "nyew",
    "nyew-nyew",
    "nyoo",
    "nyuu",
    "nyuuu",
    "meww",
    "mewww",
    "meew",
    "meeeow",
    "meoooow",
    "meooooow",
    "maau",
    "mau",
    "mao",
    "māo",
    "mau-mau",
    "mao-mao",
    "miau-miauu",
    "miaoow",
    "miaw",
    "miauw",
    "mjau-mjauu",
    "miyav-miyav",
    "miyau-miyau",
    "miyow-miyow",
    "miau-nyan",
    "meow-nya",
    "nya-meow",
    "mew-nya",
    "meow!",
    "meow!!",
    "meow?",
    "meow~",
    "meow~~",
    "meow...",
    "meow-",
    "meow<3",
    "meow :3",
    "meow uwu",
    "meow owo",
    "meow nya",
    "meow nyan",
    "meow mew",
    "meow purrr",
    "meow rawr",
    "meow pls",
    "meow lol",
    "meow hehe",
    "meow heheh",
    "meow softly",
    "meow loudly",
    "meow sleepy",
    "meow tiny",
    "meow big",
    "meow cute",
    "meow angry",
    "meow happy",
    "meow sad",
    "meow royal",
    "meow goblin",
    "meow wizard",
    "meow pirate",
    "meow robot",
    "meow alien",
    "meow ghost",
    "meow demon",
    "meow angel",
    "meow baby",
    "meow boss",
    "meow gamer",
    "meow zoomie",
    "meow midnight",
    "meow moon",
    "meow sun",
    "meow star",
    "meow cloud",
    "meow thunder",
    "meow whisper",
    "meow chirp",
    "meow trill",
    "meow squeak",
    "meow roar",
    "miaow!",
    "miaow!!",
    "miaow?",
    "miaow~",
    "miaow~~",
    "miaow...",
    "miaow-",
    "miaow<3",
    "miaow :3",
    "miaow uwu",
    "miaow owo",
    "miaow nya",
    "miaow nyan",
    "miaow mew",
    "miaow purrr",
    "miaow rawr",
    "miaow pls",
    "miaow lol",
    "miaow hehe",
    "miaow heheh",
    "miaow softly",
    "miaow loudly",
    "miaow sleepy",
    "miaow tiny",
    "miaow big",
    "miaow cute",
    "miaow angry",
    "miaow happy",
    "miaow sad",
    "miaow royal",
    "miaow goblin",
    "miaow wizard",
    "miaow pirate",
    "miaow robot",
    "miaow alien",
    "miaow ghost",
    "miaow demon",
    "miaow angel",
    "miaow baby",
    "miaow boss",
    "miaow gamer",
    "miaow zoomie",
    "miaow midnight",
    "miaow moon",
    "miaow sun",
    "miaow star",
    "miaow cloud",
    "miaow thunder",
    "miaow whisper",
    "miaow chirp",
    "miaow trill",
    "miaow squeak",
    "miaow roar",
    "mew!",
    "mew!!",
    "mew?",
    "mew~",
    "mew~~",
    "mew...",
    "mew-",
    "mew<3",
    "mew :3",
    "mew uwu",
    "mew owo",
    "mew nya",
    "mew nyan",
    "mew mew",
    "mew purrr",
    "mew rawr",
    "mew pls",
    "mew lol",
    "mew hehe",
    "mew heheh",
    "mew softly",
    "mew loudly",
    "mew sleepy",
    "mew tiny",
    "mew big",
    "mew cute",
    "mew angry",
    "mew happy",
    "mew sad",
    "mew royal",
    "mew goblin",
    "mew wizard",
    "mew pirate",
    "mew robot",
    "mew alien",
    "mew ghost",
    "mew demon",
    "mew angel",
    "mew baby",
    "mew boss",
    "mew gamer",
    "mew zoomie",
    "mew midnight",
    "mew moon",
    "mew sun",
    "mew star",
    "mew cloud",
    "mew thunder",
    "mew whisper",
    "mew chirp",
    "mew trill",
    "mew squeak",
    "mew roar",
    "miau!",
    "miau!!",
    "miau?",
    "miau~",
    "miau~~",
    "miau...",
    "miau-",
    "miau<3",
    "miau :3",
    "miau uwu",
    "miau owo",
    "miau nya",
    "miau nyan",
    "miau mew",
    "miau purrr",
    "miau rawr",
    "miau pls",
    "miau lol",
    "miau hehe",
    "miau heheh",
    "miau softly",
    "miau loudly",
    "miau sleepy",
    "miau tiny",
    "miau big",
    "miau cute",
    "miau angry",
    "miau happy",
    "miau sad",
    "miau royal",
    "miau goblin",
    "miau wizard",
    "miau pirate",
    "miau robot",
    "miau alien",
    "miau ghost",
    "miau demon",
    "miau angel",
    "miau baby",
    "miau boss",
    "miau gamer",
    "miau zoomie",
    "miau midnight",
    "miau moon",
    "miau sun",
    "miau star",
    "miau cloud",
    "miau thunder",
    "miau whisper",
    "miau chirp",
    "miau trill",
    "miau squeak",
    "miau roar",
    "miao!",
    "miao!!",
    "miao?",
    "miao~",
    "miao~~",
    "miao...",
    "miao-",
    "miao<3",
    "miao :3",
    "miao uwu",
    "miao owo",
    "miao nya",
    "miao nyan",
    "miao mew",
    "miao purrr",
    "miao rawr",
    "miao pls",
    "miao lol",
    "miao hehe",
    "miao heheh",
    "miao softly",
    "miao loudly",
    "miao sleepy",
    "miao tiny",
    "miao big",
    "miao cute",
    "miao angry",
    "miao happy",
    "miao sad",
    "miao royal",
    "miao goblin",
    "miao wizard",
    "miao pirate",
    "miao robot",
    "miao alien",
    "miao ghost",
    "miao demon",
    "miao angel",
    "miao baby",
    "miao boss",
    "miao gamer",
    "miao zoomie",
    "miao midnight",
    "miao moon",
    "miao sun",
    "miao star",
    "miao cloud",
    "miao thunder",
    "miao whisper",
    "miao chirp",
    "miao trill",
    "miao squeak",
    "miao roar",
    "miaou!",
    "miaou!!",
    "miaou?",
    "miaou~",
    "miaou~~",
    "miaou...",
    "miaou-",
    "miaou<3",
    "miaou :3",
    "miaou uwu",
    "miaou owo",
    "miaou nya",
    "miaou nyan",
    "miaou mew",
    "miaou purrr",
    "miaou rawr",
    "miaou pls",
    "miaou lol",
    "miaou hehe",
    "miaou heheh",
    "miaou softly",
    "miaou loudly",
    "miaou sleepy",
    "miaou tiny",
    "miaou big",
    "miaou cute",
    "miaou angry",
    "miaou happy",
    "miaou sad",
    "miaou royal",
    "miaou goblin",
    "miaou wizard",
    "miaou pirate",
    "miaou robot",
    "miaou alien",
    "miaou ghost",
    "miaou demon",
    "miaou angel",
    "miaou baby",
    "miaou boss",
    "miaou gamer",
    "miaou zoomie",
    "miaou midnight",
    "miaou moon",
    "miaou sun",
    "miaou star",
    "miaou cloud",
    "miaou thunder",
    "miaou whisper",
    "miaou chirp",
    "miaou trill",
    "miaou squeak",
    "miaou roar",
    "nya!",
    "nya!!",
    "nya?",
    "nya~",
    "nya~~",
    "nya...",
    "nya-",
    "nya<3",
    "nya :3",
    "nya uwu",
    "nya owo",
    "nya nya",
    "nya nyan",
    "nya mew",
    "nya purrr",
    "nya rawr",
    "nya pls",
    "nya lol",
    "nya hehe",
    "nya heheh",
    "nya softly",
    "nya loudly",
    "nya sleepy",
    "nya tiny",
    "nya big",
    "nya cute",
    "nya angry",
    "nya happy",
    "nya sad",
    "nya royal",
    "nya goblin",
    "nya wizard",
    "nya pirate",
    "nya robot",
    "nya alien",
    "nya ghost",
    "nya demon",
    "nya angel",
    "nya baby",
    "nya boss",
    "nya gamer",
    "nya zoomie",
    "nya midnight",
    "nya moon",
    "nya sun",
    "nya star",
    "nya cloud",
    "nya thunder",
    "nya whisper",
    "nya chirp",
    "nya trill",
    "nya squeak",
    "nya roar",
    "nyan!",
    "nyan!!",
    "nyan?",
    "nyan~",
    "nyan~~",
    "nyan...",
    "nyan-",
    "nyan<3",
    "nyan :3",
    "nyan uwu",
    "nyan owo",
    "nyan nya",
    "nyan nyan",
    "nyan mew",
    "nyan purrr",
    "nyan rawr",
    "nyan pls",
    "nyan lol",
    "nyan hehe",
    "nyan heheh",
    "nyan softly",
    "nyan loudly",
    "nyan sleepy",
    "nyan tiny",
    "nyan big",
    "nyan cute",
    "nyan angry",
    "nyan happy",
    "nyan sad",
]


async def meow(ctx: CommandContext, message: str) -> object | None:
    meow = random.choice(MEOWS)
    return await ctx.reply(meow)
